- name: install psycopg2-binary
  ansible.builtin.pip:
    name: psycopg2-binary
    state: present

- name: create postgres database
  community.postgresql.postgresql_db:
    name: "{{ item.name }}"
    encoding: "{{ item.encoding | default(omit) }}"
    conn_limit: "{{ item.conn_limit | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    trust_input: "{{ item.trust_input | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    login_unix_socket: "{{ postgres_socket_directory }}"
  loop: "{{ postgres_databases }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - postgres_databases is defined
  become_user: postgres
  become: yes

- name: create postgres users
  community.postgresql.postgresql_user:
    name: "{{ item.name }}"
    db: "{{ item.db | default(omit) }}"
    password: "{{ item.password }}"
    expires: "{{ item.expires | default(omit) }}"
    port: "{{ postgres_port }}"
    login_unix_socket: "{{ postgres_socket_directory  | default(omit) }}"
    role_attr_flags: "{{ item.role_attr_flags  | default(omit) }}"
  loop: "{{ postgres_users }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - postgres_users is defined
  become_user: postgres
  become: yes
