---
# tasks file for postgres
- name: import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install postgres
  ansible.builtin.package:
    name: "{{ postgres_packages }}"
    state: present
  notify:
    - systemctl daemon-reexec

- name: configure as Master
  ansible.builtin.import_tasks: master.yml
  when:
    - is_postgres_master == True

- name: configure as Replica
  ansible.builtin.import_tasks: replica.yml
  when:
    - is_postgres_master != True
